### PR TITLE
Allow using aind-data-schema-models classes natively

### LINKED ISSUE #58: Allow aind-data-schema-models Platform and Modality to be used natively
Due to https://github.com/AllenNeuralDynamics/aind-data-schema/issues/960, it is currently impossible to use the two classes as dictionary keys in our models. To go around that, we are currently using the abbreviation of each class as the allow input. for instance:

https://github.com/AllenNeuralDynamics/aind-watchdog-service/blob/6207b3a044338195663f3130b011300d185030cd/src/aind_watchdog_service/models/manifest_config.py#L24-L27

https://github.com/AllenNeuralDynamics/aind-watchdog-service/blob/6207b3a044338195663f3130b011300d185030cd/src/aind_watchdog_service/models/manifest_config.py#L79

One could go around this by implementing BeforeValidators in both these classes that take as input the class and return the abbreviation.

### PR DESCRIPTION
**Pull request by bruno-f-cruz**
Closes #58 

Unfortunately, because these classes are implemented upstream it's hard to provide proper type hints and still ensure proper schema compilation. This is the best I could think of for now.

### CODE REVIEW

**Comment by bruno-f-cruz** [comment]
Not sure what is going on with the CD/CI but tests are passing on my local machine with a clean environment. Can someone else tests it?

**Comment by jtyoung84** [comment]
It looks like the acq datetime is off a little:
```
ManifestConfig(name='test', processor_full_name='na', subject_id=7, acquisition_datetime=datetime.datetime(2024, 9, 3, 9, 18, 29, 186489), schedule_time=None, force_cloud_sync=False, transfer_endpoint='http://aind-data-transfer-service/api/v1/submit_jobs', platform='behavior', capsule_id=None, mount=None, s3_bucket=<BucketType.PRIVATE: 'private'>, project_name='no project', destination='path', modalities={'behavior': ['path']}, schemas=['path'], script={}) != ManifestConfig(name='test', processor_full_name='na', subject_id=7, acquisition_datetime=datetime.datetime(2024, 9, 3, 9, 18, 29, 186436), schedule_time=None, force_cloud_sync=False, transfer_endpoint='http://aind-data-transfer-service/api/v1/submit_jobs', platform='behavior', capsule_id=None, mount=None, s3_bucket=<BucketType.PRIVATE: 'private'>, project_name='no project', destination='path', modalities={'behavior': ['path']}, schemas=['path'], script={})

Expected :ManifestConfig(name='test', processor_full_name='na', subject_id=7, acquisition_datetime=datetime.datetime(2024, 9, 3, 9, 18, 29, 186436), schedule_time=None, force_cloud_sync=False, transfer_endpoint='http://aind-data-transfer-service/api/v1/submit_ ...

Actual   :ManifestConfig(name='test', processor_full_name='na', subject_id=7, acquisition_datetime=datetime.datetime(2024, 9, 3, 9, 18, 29, 186489), schedule_time=None, force_cloud_sync=False, transfer_endpoint='http://aind-data-transfer-service/api/v1/submit_ ...

```

**Review by arielleleon — COMMENTED** [review]
@bruno-f-cruz - I tested this change out but I do not see type hints with the extra logic. Maybe I am missing something?

**Comment by arielleleon** [comment]
Got it, I misunderstood that.

**Review by arielleleon — APPROVED** [review]

**Pull request merged**
